services:
  - type: web
    name: beachrank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: MONGO_URI
        sync: false
        # If you want to set it directly here (not recommended for security):
        # value: mongodb+srv://user:YOUR_PASSWORD@clustersanndmatch.kvu15.mongodb.net/?retryWrites=true&w=majority&appName=ClusterSanndMatch
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOW_ENV_DEBUG
        value: 'true' # Set to 'false' when not debugging 