@echo off
cd /d "%~dp0"
echo Activating virtual environment...
call venv\Scripts\activate
echo Running app.py...
python app.py
echo.
echo Deactivating virtual environment...
call deactivate
echo.
echo Script finished. Press any key to exit...
pause